/*
 * Expresso
 * parser_wrapper.h
 *
 * Header file for the functions and data structures for adapting the
 * Expresso parser generated by ANTLR4 in C++ with the C code in Expresso.
 *
 * Expresso is an interactive command-line tool for evaluating expressions.
 * Expresso supports basic data types (integers, characters, strings),
 * literals, operators (arithmetic, logical, comparison, bitwise, string
 * manipulation), and nested expressions using C syntax (e.g., precedence,
 * parentheses). Key constraint: No mutable state—every input is a pure
 * expression that evaluates to an immutable value.
 *
 * ========================================================================
 *
 * © Copyright 2025 Alfonso Guerra
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *  *  Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *  *  Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *
 *  *  Neither the name of the copyright holder nor the names of
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
#ifndef EXPRESSO_PARSER_WRAPPER_H
#define EXPRESSO_PARSER_WRAPPER_H

#include "value.h"

#ifdef __cplusplus
extern "C" {
#endif

// Forward declaration of the opaque parser context and parse tree
typedef struct ExpressoParserContext ExpressoParserContext;
typedef struct ExpressoParseTree ExpressoParseTree;

// Function to create a new parser instance
ExpressoParserContext* expresso_parser_create(void);

// Function to parse an expression string
// Returns the parse tree on success, NULL on syntax error
ExpressoParseTree* expresso_parser_parse(ExpressoParserContext* ctx, const char* expression_str);

// Get the raw text of a parse tree node
const char* expresso_tree_get_text(ExpressoParseTree* tree);

// Get the type of a parse tree node (returns rule index or -1 for terminal)
int expresso_tree_get_type(ExpressoParseTree* tree);

// Get the number of children of a parse tree node
int expresso_tree_get_child_count(ExpressoParseTree* tree);

// Get a child of a parse tree node by index
ExpressoParseTree* expresso_tree_get_child(ExpressoParseTree* tree, int index);

// Free a parse tree
void expresso_tree_destroy(ExpressoParseTree* tree);

int expresso_tree_get_terminal_type(ExpressoParseTree* tree);

typedef struct CExpressoVisitor CExpressoVisitor;

typedef Value (*CVisitFunction)(CExpressoVisitor* visitor, ExpressoParseTree* tree);

struct CExpressoVisitor {
    void* user_data;
    CVisitFunction visit_expression;
    CVisitFunction visit_additive_expression;
    CVisitFunction visit_multiplicative_expression;
    CVisitFunction visit_literal;
};

Value expresso_tree_accept(ExpressoParseTree* tree, CExpressoVisitor* visitor);

// Function to destroy the parser instance
void expresso_parser_destroy(ExpressoParserContext* ctx);

#ifdef __cplusplus
}
#endif

#endif // EXPRESSO_PARSER_WRAPPER_H
